steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-demo-app-prod:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-demo-app-prod:$COMMIT_SHA']
- name: 'gcr.io/google-cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'flask-demo-app-prod', '--image', 'gcr.io/$PROJECT_ID/flask-demo-app-prod:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/flask-demo-app-prod:$COMMIT_SHA